services:
  - type: web
    name: chemical-equipment-backend
    env: python
    rootDirectory: backend
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn chemical_equipment.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: your-backend.onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://your-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend.onrender.com
      - key: DATABASE_URL
        fromDatabase: true
        name: chemical-equipment-db

  - type: web
    name: chemical-equipment-frontend
    env: static
    rootDirectory: frontend-web
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://your-backend.onrender.com/api

databases:
  - name: chemical-equipment-db
    plan: free
