services:
  - type: web
    name: chemical-equipment-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn chemical_equipment.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: your-backend.onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://your-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: chemical-equipment-db
          property: connectionString

  - type: web
    name: chemical-equipment-frontend
    env: static
    buildCommand: cd frontend-web && npm install && npm run build
    staticPublishPath: frontend-web/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://your-backend.onrender.com/api

databases:
  - name: chemical-equipment-db
    plan: free
